name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: start bot
      run: apt update && apt upgrade -y
      run: apt install git ffmpeg -y
      run: pip3 install -U pip
      run: pip3 install -Ur requirements.txt \
      run: python3 notemusic/__main__.py
