name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: start bot
      run: | apt update && apt upgrade -y \
apt install git ffmpeg -y \
pip3 install -U pip \
mkdir /app/ \
workdir /app/ \
cp . /app/ \
pip3 install -Ur requirements.txt \
python3 notemusic/__main__.py
